<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UserSecretsId>12049d87-d7ca-4b1a-8537-15201d66fb70</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orange.Api\Orange.Api.csproj" />
    <ProjectReference Include="..\Orange.ServiceDefaults\Orange.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
