<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UserSecretsId>dotnet-Orange.Bot-32e4ca96-de7a-4abf-934b-950845af282d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Seq" Version="13.5.1" />
    <PackageReference Include="Discord.Net" Version="3.20.1" />
    <PackageReference Include="Discord.Net.Interactions" Version="3.20.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orange.ServiceDefaults\Orange.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>
</Project>
