<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <UserSecretsId>c02d5bad-f92b-4113-a08b-d99321781025</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orange.ServiceDefaults\Orange.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
